[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/Inicio.dc.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
